[phases.setup]
nixPkgs = ["php83", "php83Extensions.mongodb", "php83Extensions.gd", "php83Extensions.zip", "php83Extensions.curl", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.intl", "php83Extensions.tokenizer", "php83Extensions.ctype", "php83Extensions.fileinfo", "php83Extensions.openssl", "php83Extensions.bcmath", "composer", "apacheHttpd"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "apache2 -D FOREGROUND"